#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]
	then echo "Please run as root."
	exit
fi

dnf -y upgrade

dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

dnf swap -y mesa-va-drivers mesa-va-drivers-freeworld
dnf swap -y mesa-vdpau-drivers mesa-vdpau-drivers-freeworld

dnf remove -y firefox firefox-langpacks gnome-maps totem gnome-boxes gnome-weather \
            gnome-tour cheese rhythmbox baobab gnome-connections gnome-logs mediawriter \
            simple-scan gnome-contacts gnome-abrt gnome-classic-session libreoffice* \
            gnome-characters gnome-font-viewer gnome-calculator gnome-text-editor \
            gnome-system-monitor gnome-software PackageKit \
            PackageKit-gstreamer-plugin PackageKit-gtk3-module PackageKit-glib  

dnf swap --best --allowerasing -y ffmpeg-free ffmpeg
           
dnf install -y adw-gtk3-theme easyeffects gnome-tweaks gnome-shell-extension-appindicator \
	        gnome-shell-extension-just-perfection p7zip p7zip-plugins chromium mpv \
            papirus-icon-theme htop yt-dlp opus-tools rsms-inter-fonts 

dnf install -y zsh zsh-syntax-highlighting tmux micro wl-clipboard gedit stow g++ \
            go npm python3-pip awscli2 
