#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]
	then echo "Please run as root."
	exit
fi

rpm-ostree cancel

rpm-ostree override remove firefox firefox-langpacks
rpm-ostree install adw-gtk3-theme papirus-icon-theme stow distrobox \
					gnome-tweaks gnome-shell-extension-just-perfection \
					gnome-shell-extension-appindicator alacritty