#!/usr/bin/env bash

if [ "$EUID" -eq 0 ]
	then echo "Please don't run this as root."
	exit
fi

flatpak remove -y mediawriter contacts cheese connections \
					evince eog logs maps weather baobab font-viewer

flatpak remote-modify flathub --enable

flatpak install flathub -y org.chromium.Chromium org.gnome.World.Secrets \
							org.gtk.Gtk3theme.adw-gtk3 org.gtk.Gtk3theme.adw-gtk3-dark \
							org.gnome.Loupe org.gnome.Evince org.prismlauncher.PrismLauncher \
							io.github.spacingbat3.webcord de.haeckerfelix.Fragments \
							com.github.tchx84.Flatseal io.bassi.Amberol com.dec05eba.gpu_screen_recorder \
							org.nicotine_plus.Nicotine org.telegram.desktop org.gnome.Boxes \
							com.brave.Browser io.mpv.Mpv

gnome-shell-extension-tool -d background-logo@fedorahosted.org
gnome-shell-extension-tool -e just-perfection-desktop@just-perfection
gnome-shell-extension-tool -e appindicatorsupport@rgcjonas.gmail.com

gsettings set org.gnome.shell.keybindings toggle-application-view []
gsettings set org.gnome.shell.keybindings toggle-overview []

gsettings set org.gnome.shell.app-switcher current-workspace-only true
gsettings set org.gnome.mutter dynamic-workspaces false
gsettings set org.gnome.mutter center-new-windows true
gsettings set org.gnome.desktop.session idle-delay "uint32 0"

gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>a']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>s']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>d']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>f']"
gsettings set org.gnome.desktop.wm.keybindings close "['<Shift><Super>q']"

gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
gsettings set org.gnome.desktop.interface show-battery-percentage true
gsettings set org.gnome.shell.extensions.just-perfection workspace false
gsettings set org.gnome.shell.extensions.just-perfection window-picker-icon false
gsettings set org.gnome.shell.extensions.just-perfection search false

gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
gsettings set org.gnome.desktop.interface font-name 'Noto Sans 11'
gsettings set org.gnome.desktop.interface document-font-name 'Noto Sans 11'
gsettings set org.gnome.desktop.interface monospace-font-name 'Noto Sans Mono 10'
gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Noto Sans Bold 11'

gsettings set org.gnome.settings-daemon.plugins.power power-button-action 'interactive'
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'

gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding "<Super>k"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command "alacritty"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name "Alacritty"

gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ binding "<Super>Return"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ command "gnome-terminal"
gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ name "Terminal"

mkdir $HOME/WorkBox
distrobox create --pull --image docker.io/library/archlinux:latest --home $HOME/WorkBox --name WorkBox

mkdir $HOME/HomeBox
distrobox create --image docker.io/library/archlinux:latest --home $HOME/HomeBox --name HomeBox