#!/usr/bin/env bash

sudo pacman -Syu
sudo pacman -Sy base-devel gnupg git openssh curl npm terraform aws-cli-v2 \
                neovim ripgrep fd

git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
